name: antiradar
description: AntiRadar App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  shared_preferences: ^2.2.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  geofence_service: ^5.0.0
  flutter_otp_text_field: ^1.1.1
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true
  fonts:
    - family: TextFont
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
    - family: TitleFont
      fonts:
        - asset: assets/fonts/RaviPrakash-Regular.ttf


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700