name: antiradar
description: AntiRadar App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.2

  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0

  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  shared_preferences: ^2.2.2
  geofence_service: ^5.0.0

  pinput: ^3.0.1
  flutter_tts: ^3.8.5
  flutter_screenutil: ^5.9.0
  flutter_otp_text_field: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  generate: true
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true
  fonts:
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
    - family: RaviPrakash
      fonts:
        - asset: assets/fonts/RaviPrakash-Regular.ttf


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700