// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1afdJ8WQO0eoLB8TIfPCZH-s4DwEf8eM',
    appId: '1:311184831193:web:59a7a88fa682436af2c4c8',
    messagingSenderId: '311184831193',
    projectId: 'yolda-3c0a7',
    authDomain: 'yolda-3c0a7.firebaseapp.com',
    storageBucket: 'yolda-3c0a7.appspot.com',
    measurementId: 'G-RV865ENMEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT9R9eyqQY9JVGbWNnFLwq2Ww8goB2vTM',
    appId: '1:311184831193:android:dd7c5a23b6bdb658f2c4c8',
    messagingSenderId: '311184831193',
    projectId: 'yolda-3c0a7',
    storageBucket: 'yolda-3c0a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3g1s7RuZ3tIILbuZ_fmUlsHkoyWRVgtI',
    appId: '1:311184831193:ios:a625682ac5ff2c46f2c4c8',
    messagingSenderId: '311184831193',
    projectId: 'yolda-3c0a7',
    storageBucket: 'yolda-3c0a7.appspot.com',
    iosBundleId: 'uz.practicum.antiradar',
  );
}
